### ISSUE TITLE
Error dependencies

### ISSUE THREAD

**Issue by aamesaa** [bliblidotcom/training-unit-test#67]
Di local, tidak terjadi error, tapi saat di push kemudian pull-request, muncul error seperti dibawah ini. Apakah ada saran ? Terima kasih.

[ERROR] Failed to execute goal on project springboot: Could not resolve dependencies for project com.example:springboot:jar:0.0.1-SNAPSHOT: Could not transfer artifact com.example:springboot:jar:0.0.1-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: Unknown host nexus.codehaus.org -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project springboot: Could not resolve dependencies for project com.example:springboot:jar:0.0.1-SNAPSHOT: Could not transfer artifact com.example:springboot:jar:0.0.1-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org

**Comment by andirdju** [comment]
check review comment on #69
